### ISSUE TITLE
тупик - проблема

### ISSUE THREAD

**Issue by perece** [jcoder39/dijkstra#1]
если есть "тупик" (вершина, в которую ведет одно единственное ребро, и это ребро самое короткое, возвращается -1. если поменять местами старт и финиш - все Ok.
во всех прочих смена направления не влияет на результат.

---- до 6 от 2 ближе, чем от 2 до какой-либо другой:
> select topo_dist('{1,2,3,4,5,6}'::int[], array[row(1,2,1.1), row(2,3,4), row(2,4,2.2), row(3,5,4), row(4,5,9), row(6,2,0.6)]::topo_edge[], 1, 5);
 topo_dist 
        -1

---- тот же граф, но считаем в обратную сторону, из 5 в 1:
> select topo_dist('{1,2,3,4,5,6}'::int[], array[row(1,2,1.1), row(2,3,4), row(2,4,2.2), row(3,5,4), row(4,5,9), row(6,2,0.6)]::topo_edge[], 5, 1);
    topo_dist     
 9.10000038146973

---- выбросили 6ю ноду, считаем из 1 в 5:
> select placer.topo_dist('{1,2,3,4,5}'::int[], array[row(1,2,1.1), row(2,3,4), row(2,4,2.2), row(3,5,4), row(4,5,9)]::placer.topo_edge[], 1, 5);
    topo_dist
 9.10000038146973

---- и в обратную сторону:
> select placer.topo_dist('{1,2,3,4,5}'::int[], array[row(1,2,1.1), row(2,3,4), row(2,4,2.2), row(3,5,4), row(4,5,9)]::placer.topo_edge[], 5, 1);
    topo_dist     
 9.10000038146973

---- та же топология, что в #1, но от 6 до 2 дальше, чем от 2 до 4 (при этом оптимальный путь ведет _не_ через 4, и он находится верно)
> select topo_dist('{1,2,3,4,5,6}'::int[], array[row(1,2,1.1), row(2,3,4), row(2,4,2.2), row(3,5,4), row(4,5,9), row(6,2,2.3)]::topo_edge[], 1, 5);
    topo_dist     
 9.10000038146973

**Comment by jcoder39** [comment]
fixed
